resource "local_file" "pets" {
  filename = var.filename
  content = var.content["statement-2"]
}

resource "random_pet" "my-pet" {
  prefix = var.prefix[0]
  separator = var.separator
  length = var.length[0]
}

output "pet-name" {
  value = random_pet.my-pet.id
  description = "record the value of pet ID generated by the random_pet resourse"
}